### ISSUE TITLE
AttributeError:'Tensor' object has no attribute 'logical_not'

### ISSUE THREAD

**Issue by billtiger** [xialuxi/CircleLoss_Face#1]

**Comment by xialuxi** [comment]
2选１
1、use pytorch 1.4+
2、mask = one_hot.logical_not()  --->　make = 1.0 - mask

**Comment by tuoniaoren** [comment]
请问在人脸数据集上对比ArcFace效果怎么样

**Comment by billtiger** [comment]
@xialuxi ok，thank you for your reply！

**Comment by Richard-chen3** [comment]
请问这个代码能直接用到人脸识别里面去吗

**Comment by huangpan2507** [comment]
> 2选１
> 1、use pytorch 1.4+
> 2、mask = one_hot.logical_not() ---> mask = one_hot < 0.5

pytorch 1.5.0   torchvision 0.6.0 同样不行

**Comment by xialuxi** [comment]
mask = 1.0 - mask
