### ISSUE TITLE
你好,sparse class label和一般的class label下的circle loss效果有差别吗 

### ISSUE THREAD

**Issue by xiaodaodao123** [xialuxi/CircleLoss_Face#2]
论文里面好像没有专门讲sparse的情况, 另外您的sparsecircleloss实现是不是也适用于person reid呢?

**Comment by xialuxi** [comment]
sparse这里指的是class level,也就是论文里面的对标的am-softmax的情况, pair level对标的是triplet.
适用于人脸识别和行人reid，实际使用的时候可以参考自己的数据，选择class level 和pair level，或者联合使用。

**Comment by xiaodaodao123** [comment]
哦哦, 好的, 谢谢解答
