### ISSUE TITLE
convert_label_to_similarity与one_hot的区别与应用

### ISSUE THREAD

**Issue by L-lei** [xialuxi/CircleLoss_Face#4]
您好，请问下，convert_label_to_similarity转成相识度不是应用在人脸？相同人脸之间相识度小，不同人脸相识度大。one_hot一般应用在分类中，在您的的实现中将label转one_hot用于人脸，我怎么也没想明白

**Comment by xialuxi** [comment]
convert_label_to_similarity是类似于三元组损失，用的是样本与样本之间的特征计算相似度。
one_hot是类似于分类的损失（arcface），用的是样本与需要学习的权重计算相似度。
人脸识别当然优先选用arcface类似的损失，尤其是数据规模大的时候。

**Comment by L-lei** [comment]
感谢，结合[https://zhuanlan.zhihu.com/p/116838436](url)理解了
